### ISSUE TITLE
A short summary

### ISSUE THREAD

**Issue by mathaszip** [aau-giraf/Visual-tangible-artefacts#1]
## Description
**Describe the bug** \

**To Reproduce**

**Expected behavior** \

**Actual behavior and screenshots** \
A clear and concise description of what actually happened.

## Sub Tasks
*Create your own subtask issues on GitHub and link them here in a list.*
- [ ] \<Subtask link>

**Comment by PG2W** [comment]
review this @Kragemand

**Comment by PG2W** [comment]
pls @Kragemand
