### ISSUE TITLE
The user should be able to have a board on which visual artefacts can be placed

### ISSUE THREAD

**Issue by Kragemand** [aau-giraf/visual-tangible-artefacts#2]
Front page of the app. A Flutter component developed to be a canvas on which artefacts can be placed. The position of the artefact should be editable based on cursor position.
The front page should include the ability to delete artefacts and have a "quick talk menu".

**Comment by mLario1999** [comment]
### Subtask
Create artifact widget

**Comment by mLario1999** [comment]
### Subtask 2
Create board

**Comment by mLario1999** [comment]
### Subtask 2

Create quick actions

**Comment by mLario1999** [comment]
### Subtask 4

create artifact delete area

**Comment by mLario1999** [comment]
### Subtask 5

create switch to directional board
